[versions]
accompanist = "0.36.0"
coilVersion = "3.0.0"
composeBom = "2024.10.00"
composeShimmer = "1.0.5"
espressoCore = "3.6.1"
firebaseAdmin = "9.2.0"
junit = "1.2.1"
kotlinxCoroutines = "1.9.0"
kotlinxDatetime = "0.6.0"
kotlinxSerializationJson = "1.7.3"
ktor = "3.0.0"
ktlint = "12.1.1"
ktx = "1.13.1"
appCompat = "1.7.0"
material = "1.12.0"
material3Desktop = "1.6.11"
materialIconsExtended = "1.7.4"
postgresSocketFactory = "1.15.1"
room = "2.7.0-alpha10"
compose = "2.8.6"
navigation-compose = "2.8.3"
agp = "8.7.2"
kotlin = "2.0.21"
compose-compiler = "1.5.15"
composeTest = "1.7.4"
webWorkerDriver = "2.0.0"
writeopia = "0.4.1"
mockk = "1.13.8"
sqldelight = "2.0.0"
ksp = "2.0.21-1.0.25"
compose-multiplatform = "1.6.11"
dag-command = "1.11.0"
dokka = "1.9.20"
nexus-publish = "2.0.0"
spring-boot = "3.1.5"
spring-dependencyManagement = "1.1.3"
firebase = "33.5.1"
google-services = "4.4.2"
logback-classic = "1.5.0"
hikaricp = "5.1.0"
postgresql = "42.6.0"
compose-navigation = "2.7.0-alpha07"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-activity-compose = { module = "androidx.activity:activity-compose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-compose-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeTest" }
androidx-compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeTest" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilVersion" }
coil-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coilVersion" }
coil-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coilVersion" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "composeShimmer" }
firebase-admin = { module = "com.google.firebase:firebase-admin", version.ref = "firebaseAdmin" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlin-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-flow = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-flow", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm" }
ktor-server-websocket = { module = "io.ktor:ktor-server-websockets-jvm" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm" }
ktor-server-tests = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#material3-desktop = { module = "org.jetbrains.compose.material3:material3-desktop", version.ref = "material3" }
sql-postgres-socket-factory = { module = "com.google.cloud.sql:postgres-socket-factory", version.ref = "postgresSocketFactory" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose" }
runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
sqldelight-jvm = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
sqldelight-jdbc-driver = { group = "app.cash.sqldelight", name = "jdbc-driver", version.ref = "sqldelight" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic" }
database-hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
database-postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
sqldelight-web-driver = { module = "app.cash.sqldelight:web-worker-driver", version.ref = "webWorkerDriver" }


[plugins]
application = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
nativeCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization",  version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
dag-command = { id = "io.github.leandroborgesferreira.dag-command", version.ref = "dag-command" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-kotlin = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-dependencyManagement" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
ktor-framework = { id = "io.ktor.plugin", version.ref = "ktor" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint"}
compose-multiplatform-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
