[versions]
accompanistSystemuicontroller = "0.30.1"
coilVersion = "2.3.0"
composeBom = "2023.06.01"
espressoCore = "3.5.1"
junit = "1.1.5"
junitVersion = "4.13.2"
kotlinxCoroutinesTest = "1.7.2"
ktx = "1.10.1"
appCompat = "1.6.1"
material = "1.9.0"
materialIconsExtended = "1.4.3"
room = "2.5.2"
compose = "2.6.1"
navigation-compose = "2.6.0"
junit4-compose = "1.4.3"
agp = "8.2.0-alpha12"
kotlin = "1.9.0"
compose-compiler = "1.5.1"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilVersion" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coilVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose" }
runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "junit4-compose" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "junit4-compose" }
composeCompiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
