[versions]
accompanistSystemuicontroller = "0.30.1"
amplify = "2.11.1"
coilVersion = "2.3.0"
composeBom = "2023.06.01"
coreKotlin = "2.11.1"
desugar_jdk_libs = "2.0.3"
espressoCore = "3.5.1"
junit = "1.1.5"
junitVersion = "4.13.2"
kotlinxCoroutinesTest = "1.7.2"
kotlinxSerializationJson = "1.5.1"
ktx = "1.10.1"
appCompat = "1.6.1"
material = "1.9.0"
materialIconsExtended = "1.4.3"
room = "2.5.2"
compose = "2.6.1"
navigation-compose = "2.6.0"
junit4-compose = "1.4.3"
agp = "8.2.0-alpha15"
kotlin = "1.9.0"
compose-compiler = "1.5.1"
org-jetbrains-kotlin-jvm = "1.9.0"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
aws-amplifyframework-core-kotlin = { module = "com.amplifyframework:core-kotlin", version.ref = "amplify" }
aws-amplifyframework-cognito = { module = "com.amplifyframework:aws-auth-cognito", version.ref = "amplify" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilVersion" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coilVersion" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose" }
runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization",  version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
